# Menus
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: /logo.png
    profile:
        enabled: true
        avatar:
        gravatar: ryomahan1996@gmail.com
        author: Ryoma
        author_title: 毕己一生，依依东望。
        location: Jinan, China
        follow: https://github.com/ubuhuo/
    highlight: monokai
    sidebar: left
    category_perExpand: false
    thumbnail: true
    favicon: /favicon.ico
    # default_index_file: index.md
    social_links:
        wordpress: https://blog.blanc.site
        twitter: https://twitter.com/ryomahan1996
        weibo: https://weibo.com/xiaobaidh
        github: https://github.com/ubuhuo
        rss: /atom.xml
    social_link_tooltip: true
    aging:
        enable: true

# Widgets
widgets: # default use category only
    - category
    # - recent_posts
    # - archive
    # - tag
    - tagcloud
    - links
    
# Excerpt 
## Auto creat excerpt with not <!--more-->
## Enable will truncate auto_excerpt.lines rows in post head to replace excerpt.
auto_excerpt:
    enable: true
    lines: 1

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# History version 
# https://coding.net/u/ubuhuo/p/wiki_blanc/edit/master/source/_posts/分类/分类/名字.md
history_control: # make you wiki has history version control in page
    enable: true
    server_link: https://github.com
    user: ubuhuo
    repertory: ubuhuo.github.io
    branch: backups

# Comment
comment:
    valine:
        enable: true
        valine_id: sz7ny95XiYWkxht3H3YDs2GX-gzGzoHsz
        valine_key: T8JJugDkbqtFLONIIzcPWW76

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true
    justifiedgallery: true
    mathjax: true
    google_analytics: UA-110100486-1
    google_site_verification: D9ld5oQABBxIwNpgD_WN61p51-ZcABZ6Olt4HKcxlWw
    baidu_analytics: fac7e69191f0847b886888aa7c794fa7
    busuanzi_count: true

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
      依依东望: https://www.blanc.site
      一只小白: https://blog.blanc.site
      小白维基: https://wiki.blanc.site
