name: Deploy Blog

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2-beta
      with:
        node-version: "12.x"
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        git config --global user.name 'bulabula' # 换成你自己的邮箱和名字
        git config --global user.email 'bulabula@athorx.com'

        npm i -g hexo-cli # 安装hexo
        npm i
  
    - name: Deploy
      run: |
        hexo generate && hexo deploy
